CREATE TABLE users
(
    id      VARCHAR(36) PRIMARY KEY UNIQUE,
    name    VARCHAR(100) NOT NULL,
    email   VARCHAR(100) NOT NULL,
    status  VARCHAR(100) NOT NULL,
    version INTEGER DEFAULT 0
)
